# Generated by Django 4.2.4 on 2023-08-07 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_comments'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comments',
            constraint=models.CheckConstraint(check=models.Q(('upvote', False), ('downvote', False), _connector='OR'), name='upvote-downvote exclusive'),
        ),
    ]
