# Generated by Django 4.2.4 on 2023-08-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_comments_upvote_downvote_exclusive'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comments',
            name='upvote-downvote exclusive',
        ),
        migrations.AddConstraint(
            model_name='comments',
            constraint=models.CheckConstraint(check=models.Q(('upvote', False), ('downvote', False), _connector='OR'), name='upvote-downvote exclusive', violation_error_message='You cannot simultaneously upvote and downvote this comment.'),
        ),
    ]
