# Generated by Django 4.2.4 on 2023-08-09 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0011_friendship_friendrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='user',
        ),
        migrations.DeleteModel(
            name='FriendRequest',
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
