# Generated by Django 4.2.4 on 2023-08-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0013_friendship_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_Friend',
            field=models.BooleanField(default=False),
        ),
    ]
