# Generated by Django 4.2.4 on 2023-08-25 15:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0019_customuser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrendshipDetails',
            fields=[
                ('friendship_id', models.AutoField(primary_key=True, serialize=False)),
                ('person_1', models.CharField(max_length=100)),
                ('person_2', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Friendship',
        ),
    ]
