# Generated by Django 4.2.4 on 2023-08-26 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0020_frendshipdetails_delete_friendship'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
