# Generated by Django 4.2.4 on 2023-08-26 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0025_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
