# Generated by Django 4.2.4 on 2023-08-26 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0027_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
