# Generated by Django 4.2.4 on 2023-09-24 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0030_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='color_code',
            field=models.CharField(choices=[('red', 'Red'), ('green', 'Green'), ('blue', 'Blue'), ('yellow', 'Yellow')], default='red', max_length=10),
        ),
    ]
