# Generated by Django 4.2.4 on 2023-09-24 08:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Blog', '0033_alter_comments_user_commented'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='user_commented',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
